spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

  datasource:
    url: jdbc:h2:file:~/database/h2
    username: user
    password: password
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migration

#keycloak:
#  auth-server-url: http://localhost:9080/auth
#  realm: pstuEdu
#  resource: pstuEdu_client
#  public-client: true
